apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flex-gpu-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: flex-gpu-device-plugin
  template:
    metadata:
      labels:
        app: flex-gpu-device-plugin
    spec:
      hostNetwork: true
      containers:
        - image: fangangan/flex-gpu-device-plugin:dev
          imagePullPolicy: Always
          name: flex-gpu-device-plugin
          command: ["flex-gpu-device-plugin"]
          args: ["-mock=8192,8192,8192", "--v=6"]
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
