apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flex-gpu-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: flex-gpu-device-plugin
  template:
    metadata:
      labels:
        app: flex-gpu-device-plugin
    spec:
      hostNetwork: true
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: flex-gpu-device-plugin
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
